### ISSUE TITLE
Failed to deploy a faasm cluster on k8s

### ISSUE THREAD

**Issue by lyuxiaosu** [faasm/faasm#828]
Hi, I tried to deploy the faasm cluster on k8s, but failed. I git clone the faasm repo and then run `git submodule update --init --recursive `，` source ./bin/workon.sh`, the python virtual environment is sure to activate. Then I run:
`faasmctl deploy.k8s 
  --workers 1
  --context /users/xiaosuGW/.kube/config
  --ini-file ./my_faasm.init
`

However, the deployment takes so long time and not ready. I check the pods under faasm namespace:
```
(faasm) xiaosuGW@node0:/my_mount/faasm$ kubectl get pods -n faasm
NAME                            READY   STATUS                   RESTARTS   AGE
faasm-worker-5f655c78fb-7wb85   0/1     ContainerCreating        0          5m16s
faasm-worker-5f655c78fb-dhzgj   0/1     ContainerStatusUnknown   0          29m
faasm-worker-5f655c78fb-tbcss   0/1     ContainerCreating        0          29m
minio                           0/1     ContainerStatusUnknown   0          29m
planner                         1/1     Running                  0          29m
redis-queue                     0/1     ContainerCreating        0          29m
redis-state                     0/1     Completed                0          29m
upload                          0/1     ImagePullBackOff         0          29m

```

```
(faasm) xiaosuGW@node0:/my_mount/faasm$ kubectl describe pod upload -n faasm
Name:             upload
Namespace:        faasm
Priority:         0
Service Account:  default
Node:             node1.knative2.gwcloudlab-pg0.utah.cloudlab.us/128.110.219.4
Start Time:       Thu, 01 Feb 2024 09:56:23 -0700
Labels:           app=faasm
                  role=upload
Annotations:      <none>
Status:           Pending
IP:               10.244.1.32
IPs:
  IP:  10.244.1.32
Containers:
  upload:
    Container ID:
    Image:          faasm.azurecr.io/upload:0.20.1
    Image ID:
    Ports:          8002/TCP, 5000/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      REDIS_STATE_HOST:  redis-state
      REDIS_QUEUE_HOST:  redis-queue
      PLANNER_HOST:      planner
      PLANNER_PORT:      8081
      LOG_LEVEL:         info
      LD_LIBRARY_PATH:   /build/faasm/third-party/lib:/usr/local/lib
      PYTHON_CODEGEN:    off
      FAASM_WASM_VM:     wamr
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-chwqx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-chwqx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               28m                  default-scheduler  Successfully assigned faasm/upload to node1.knative2.gwcloudlab-pg0.utah.cloudlab.us
  Warning  FailedCreatePodSandBox  28m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "registry.k8s.io/pause:3.8": failed to pull image "registry.k8s.io/pause:3.8": failed to pull and unpack image "registry.k8s.io/pause:3.8": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://prod-registry-k8s-io-us-west-1.s3.dualstack.us-west-1.amazonaws.com/containers/images/sha256:4873874c08efc72e9729683a83ffbb7502ee729e9a5ac097723806ea7fa13517": dial tcp: lookup prod-registry-k8s-io-us-west-1.s3.dualstack.us-west-1.amazonaws.com on 128.110.156.4:53: server misbehaving
  Warning  Failed                  3m43s                kubelet            Failed to pull image "faasm.azurecr.io/upload:0.20.1": failed to pull and unpack image "faasm.azurecr.io/upload:0.20.1": mkdir /var/lib/containerd/io.containerd.content.v1.content/ingest/1ad97db880f3eb85b063d5b5ebf4c401dc280ebc36505954e269d40be5d6f498: no space left on device
  Warning  Failed                  3m43s                kubelet            Error: ErrImagePull
  Normal   BackOff                 3m42s                kubelet            Back-off pulling image "faasm.azurecr.io/upload:0.20.1"
  Warning  Failed                  3m42s                kubelet            Error: ImagePullBackOff
  Normal   Pulling                 3m26s (x2 over 28m)  kubelet            Pulling image "faasm.azurecr.io/upload:0.20.1"
```
It seems the `upload ` pod failed to pull the container image, is the` upload ` image accessable? Thanks for your help.

**Comment by lyuxiaosu** [comment]
The version I tried above is 0.20.1, so I tried 0.20.0, this version can deploy all pods correctly:
```
xiaosuGW@node0:/my_mount/faasm$ kubectl get pods -n faasm
NAME                            READY   STATUS    RESTARTS   AGE
faasm-worker-86b5b66b97-zkgxw   1/1     Running   0          30m
minio                           1/1     Running   0          30m
planner                         1/1     Running   0          30m
redis-queue                     1/1     Running   0          30m
redis-state                     1/1     Running   0          30m
upload                          1/1     Running   0          30m

```

However, the faasmctl keep printing:
```
Load balancer (worker-lb) not ready
Waiting for ingress IPs to be assigned
```
Where is worker-lb? It will be installed automatically? Does this log mean worker-lb is not running? But I didn't see any other pods creation under `faasm` namespace. If no load balancer, how to access faasm from outside? Thanks for your help.

**Comment by csegarragonz** [comment]
Hi!

First of all, many thanks for using Faasm!

Note that to deploy a K8s cluster you do not really need to clone the repo or the submodules.
You should be able to deploy it just using `faasmctl`.

Following the instructions [here](https://github.com/faasm/faasmctl/blob/main/docs/deploy.md#kubernetes) should be enough.
Also, the K8s deployment is tested as part of our CI/CD pipeline whenever we push a new tag [here](https://github.com/faasm/faasm/blob/main/.github/workflows/azure.yml).
So it should be working fine.

From your logs, I see the following message:
```
 Warning  Failed                  3m43s                kubelet            Failed to pull image "faasm.azurecr.io/upload:0.20.1": failed to pull and unpack image "faasm.azurecr.io/upload:0.20.1": mkdir /var/lib/containerd/io.containerd.content.v1.content/ingest/1ad97db880f3eb85b063d5b5ebf4c401dc280ebc36505954e269d40be5d6f498: no space left on device
```
it says `no space left on device`. This makes me thing that you are deploying Faasm on a cluster with insufficient disk.

I see you are deploying on AWS, how many nodes does your cluster have?
What is each node's size?

As a rule of thumb, we usually deploy as many nodes as workers we want, and use Azures `Standard_D8_v5` machines.

**Comment by lyuxiaosu** [comment]
Thanks for your reply @csegarragonz. Yes, My first post was related to the disk space. I used [Cloudlab](https://www.cloudlab.us/) to deploy k8s and faasm and its root directory is small, but I have already solved the disk space problem. Version 0.20.1 still doesn't work because of:
`upload                          0/1     ImagePullBackOff         0          29m`

I don't know why. Version 0.20.0 works, so I decide to use it for now. 

Since Cloudlab nodes don't support to create a loadblancer service with assigned external IP (leading alway a pending external IP), so the set up keep printing "Waiting for ingress IPs to be assigned" and finally no `faasm.ini` generated, other steps such as compile, upload, invoke function no way to achieve because they depend on this file. 

I think I can work around the loadbalancer pending IP problem by creating a nodePort service type and upload/invoke a function with Http requests, however, I need to compile the function code to Webassembly code first, and then I can upload it to faasm,  but I cannot find a working way to do it. 

I mainly want to build C/C++ function code to webassembly code. I tried [cpp](https://github.com/faasm/cpp), but it failed due to no `faasm.ini`. I tried [examples](https://github.com/faasm/examples) because it seems to build any applications to webassembly, but I failed with the following error:
```
(faasm-examples) xiaosuGW@node0:~/examples$ inv cli build
[+] Running 1/1
 ✔ Container examples-build-1  Started                                                                                                                                         0.5s

----------------------------------
CPP CLI
Version: 0.3.1
Project root: /code/cpp/bin/..
Mode: container
----------------------------------

Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 15.0 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    WARNING: No metadata found in ./venv/lib/python3.10/site-packages
    WARNING: No metadata found in ./venv/lib/python3.10/site-packages
    WARNING: No metadata found in ./venv/lib/python3.10/site-packages
    Uninstalling pip-22.0.2:
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/code/examples/venv/bin/pip'


----------------------------------
Faasm Examples CLI
Faasm Version: 0.17.0
CPP Version: 0.3.1
Python Version: 0.3.1
----------------------------------

```

I don't know why and stuck here. Could you please give some help for this? If I can build a C/C++ function code to webassembly for faasm, then I can use http request to upload and invoke the function. Thanks for your help.

**Comment by csegarragonz** [comment]
The LoadBalancer problem is indeed an issue.

Right now, the `faasmctl` deployment will only work if your k8s cluster supports creating a load balancer service.
In the past (for other projects) I have used both [`metallb`](https://github.com/metallb/metallb) or `NodePort` services.

What is the error reported in the `ImagePullBackoff`?
I.e. can you get the event logs for the pod?

Keep in mind that if `faasmctl` fails, you will need a way to create the `faasm.ini` file, as all tools in Faasm rely on it to do stuff.
For example, once you cross-compile a function to WebAssembly, the `cpp` container will use the `faasm.ini` file to know where to upload it.

In terms of using the `cpp` container, you should be able to, from the `faasm` repo, run:

```bash
faasmctl cli.cpp
inv func demo hello
inv func.upload demo hello
```

if this works, you do not really need to get into the `examples` repo.

**Comment by lyuxiaosu** [comment]
Thanks @csegarragonz . I turned to docker compose deployment and made it work (version 0.20.1). It's enough for me to do some basic testing. Thanks for your help.
